Finally commited updating the 'This tutorial Covers', 'At the end you…
ChildsplayOSU/bogl-docs pull request #31
Opened 2021-09-21 00:00 UTC by garrettberliner

… should be able to', and added condition definition

2021-09-25 23:02 UTC, Aidenjn requested changes
Please review the comments I left!

2021-09-25 23:02 UTC, Aidenjn commented on tutorials/boards.md
> +- Creating board & board values
I did not mention this before, but could you please put the word "and" where you see & being used in sentences? Since the & is a piece of BoGL syntax I want to leave it out of sentences describing BoGL.

2021-09-29 01:04 UTC, garrettberliner commented on Gemfile
> +gem "webrick", "~> 1.7"
Just removed it, I don't know how that was added sorry!

2021-10-04 22:09 UTC, garrettberliner commented on Gemfile
> +gem "webrick", "~> 1.7"
I just tried to run a local file without this, and my local version doesn't work without this in my Gemfile? Will bring it up at our meeting tomorrow.

2021-10-11 22:08 UTC, merged